# Generated by Django 3.1.7 on 2021-03-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210320_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Total number of likes'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='content/Aaron_Eckhart_0001.jpg', null=True, upload_to='content'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
